# Generated by Django 3.1.3 on 2020-11-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201103_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=9.99),
            preserve_default=False,
        ),
    ]
